[package]
name = "netcup-api"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.53"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5.9"
